spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: controle1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 9090



